[build]
builder = "DOCKERFILE"
dockerfilePath = "packages/api/Dockerfile"
watchPatterns = ["packages/api/**", "packages/shared/**", "packages/i18n/**", "packages/api/Dockerfile"]

[deploy]
startCommand = "node packages/api/dist/index.js"
watchPatterns = ["packages/api/**", "packages/shared/**", "packages/i18n/**", "packages/api/Dockerfile"]
