-- ─── 032: garden_tasks — source_timeline_id + DB-level idempotency ───────────
-- Adds a nullable FK from garden_tasks to plant_timeline so that tasks
-- generated by a full-diagnosis (chupchu_analysis) can be linked to the
-- timeline entry that produced them.
--
-- The partial unique index gives DB-level dedup: for any given diagnosis entry,
-- the same task title can only be inserted once per user.  NULL source_timeline_id
-- rows (custom tasks, non-sourced chupchu proposals) are excluded from the
-- uniqueness constraint — behaviour for those paths is unchanged.
--
-- title is included in the index key so the same timeline entry CAN produce
-- tasks with different titles (the normal case: one diagnosis → N tasks).
-- A retry of the exact same bulk request is silently deduplicated.
--
-- SAFE TO RE-RUN — ADD COLUMN IF NOT EXISTS + CREATE INDEX IF NOT EXISTS.

ALTER TABLE garden_tasks
  ADD COLUMN IF NOT EXISTS source_timeline_id UUID
  REFERENCES plant_timeline(id) ON DELETE SET NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_garden_tasks_source
  ON garden_tasks (user_id, source_timeline_id, title)
  WHERE source_timeline_id IS NOT NULL;
